### ISSUE TITLE
Version 3.3.0 - Minor Version Release

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1206]
This issue is for tracking all the things that need to be done before `3.3.0` release can go live.  Quite a few Upstream issues need to be resolved.

Theming
------------
* [x] ~~#1188~~
* [x] ~~gmusic-utils/gmusic-theme.js/issues/39~~
* [x] ~~gmusic-utils/gmusic-theme.js/issues/37~~
* [x] ~~gmusic-utils/gmusic-theme.js/issues/30~~
* [x] ~~gmusic-utils/gmusic-theme.js/issues/22~~

Mini Player
---------------
* [x] ~~#1026~~

Last.FM
------------
* [x] ~~#1112~~
* [x] ~~#1061~~
* [ ] #921

New Settings
-----------------
* [x] ~~#1163~~
* [x] ~~#972~~

Chromecast
----------------
* [x] #1207  <-- Epic Ticket

I will try to tackle as many of these issues as possible, if other people want to lend a hand that would be great 👍 

The easiest ones are probably the theming issues as they are just "find the CSS selector" --> "add a new rule"

Onwards and Upwards 😆

**Comment by berryelectronics** [comment]
Although the version is out, the icon seems squishied together
![ss 2016-07-03 at 01 21 38](https://cloud.githubusercontent.com/assets/12616124/16545142/41166b98-4121-11e6-849a-6bc61e71fa62.png)

I may look into it if i have the time..
