### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#122]
Should have made this issue a bit sooner, there isn't much left to do now.

- [x] Rework all the JS files, move as much as possibly into node modules
- [x] Upgrade to CEF 45 (will fix #34) --> This is a big change so might not make it into `2.0`
- [x] Rework the last.fm intergration and song alert code (will fix #89)
- [x] Try optimize the alert fading, possibly animate instead of increment (will fix #85)
- [x] Remove the Reset and Close button from the settings menu
- [x] Try to get an exe signing certificate for the installer (optional)

If anyone wants anything else added to this list raise it below and I'll look into it.

**Comment by MarshallOfSound** [comment]
Ready for release
