### ISSUE TITLE
Chromecast support tracker

### ISSUE THREAD

**Issue by MarshallOfSound** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#986]
This is just so that I can maintain information around chromecast support progress.

**Option 1**

* [ ] Need to be able to capture a [MediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream) from an HTML5 Audio Element
    * [ ] Depends on Chromes support of [captureStream()](https://w3c.github.io/mediacapture-fromelement/)
* [ ] MediaStream will be piped into a `Response` object from an [express](https://www.npmjs.com/package/express) server that will be embedded in the renderer process.

**Option 2**  
*More thought needs to be put into this*

What if we simply mocked out the existing chromecast API for electron using the [node cast](https://github.com/thibauts/node-castv2) npm module.  Inject the global chrome variables at runtime and mock it enough to receive the chromecast URL's

**Comment by jostrander** [comment]
I downloaded the CRX for chromecast and toyed around with the code trying to beautify it enough to understand what it's doing, and there is a LOT to it. I think however that it is probably the best way to get chromecast support into the desktop app as it will work natively with google's code inside the web frame.

**Comment by MarshallOfSound** [comment]
Yeah, we would have to mock out all of these methods

https://developers.google.com/cast/docs/reference/chrome/

It's a big job and should probably be done in a separate project.  Probably `electron-chromecast`

**Comment by MarshallOfSound** [comment]
Progress on this wrapper can be seen over at https://github.com/GPMDP/electron-chromecast

**Comment by MarshallOfSound** [comment]
Sneakily closes this issue to see if anyone notices @jostrander :laughing: :grin:

**Comment by jostrander** [comment]
I noticed. Lol

**Comment by Lord-Phoenix** [comment]
I noticed too 😉

**Comment by jonpolak** [comment]
I've been using `pulseaudio-dlna` which is a debian package that allows you to  [redirect audio to chromecast](http://www.webupd8.org/2016/03/how-to-stream-audio-to-chromecast-or.html) -- it's in the standard debian repo - [here's the sourcecode ](https://github.com/masmu/pulseaudio-dlna)

**Comment by toddmedema** [comment]
+1 on this issue. Don't know if it helps, but was doing other research on how to use Chromecasts and came across a Windows app that streams system sound to the Chromecast: https://github.com/acidhax/chromecast-audio-stream

**Comment by jostrander** [comment]
Chromecast alpha support should be out next release. We have a pretty good working prototype mock of the `chrome.cast` API's but its not completely finished, there is still quite a bit to implement all the features of the extension like device picker, media session management, etc.
